package org.eastwill.domain;
// Generated 2018-4-14 14:20:11 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccessToken generated by hbm2java
 */
@Entity
@Table(name = "access_token_hos", schema = "public")
public class AccessTokenHos implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String accessToken;
	private Integer expiresIn;
	private Date createTime;
	private Date expireTime;

	public AccessTokenHos() {
	}

	public AccessTokenHos(String accessToken) {
		this.accessToken = accessToken;
	}

	public AccessTokenHos(String accessToken, Integer expiresIn, Date createTime, Date expireTime) {
		this.accessToken = accessToken;
		this.expiresIn = expiresIn;
		this.createTime = createTime;
		this.expireTime = expireTime;
	}

	@Id

	@Column(name = "access_token", unique = true, nullable = false)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "expires_in")
	public Integer getExpiresIn() {
		return this.expiresIn;
	}

	public void setExpiresIn(Integer expiresIn) {
		this.expiresIn = expiresIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_time", length = 29)
	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

}
