package org.eastwill.domain;
// Generated 2018-10-17 9:42:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DictHsp generated by hbm2java
 */
@Entity
@Table(name = "dict_hsp", schema = "public")
public class DictHsp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String hspCode;
	private String hspName;
	private String organizationCode;
	private String provId;
	private String cityId;
	private String countyId;
	private String streetId;
	private String addrDetail;
	private String hosKey;
	
	public DictHsp() {
	}

	public DictHsp(String hspCode) {
		this.hspCode = hspCode;
	}

	public DictHsp(String hspCode, String hspName, String organizationCode, String provId, String cityId,
			String countyId, String streetId, String addrDetail) {
		this.hspCode = hspCode;
		this.hspName = hspName;
		this.organizationCode = organizationCode;
		this.provId = provId;
		this.cityId = cityId;
		this.countyId = countyId;
		this.streetId = streetId;
		this.addrDetail = addrDetail;
	}

	@Id

	@Column(name = "hsp_code", unique = true, nullable = false)
	public String getHspCode() {
		return this.hspCode;
	}

	public void setHspCode(String hspCode) {
		this.hspCode = hspCode;
	}

	@Column(name = "hsp_name")
	public String getHspName() {
		return this.hspName;
	}

	public void setHspName(String hspName) {
		this.hspName = hspName;
	}

	@Column(name = "organization_code")
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "prov_id")
	public String getProvId() {
		return this.provId;
	}

	public void setProvId(String provId) {
		this.provId = provId;
	}

	@Column(name = "city_id")
	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	@Column(name = "county_id")
	public String getCountyId() {
		return this.countyId;
	}

	public void setCountyId(String countyId) {
		this.countyId = countyId;
	}

	@Column(name = "street_id")
	public String getStreetId() {
		return this.streetId;
	}

	public void setStreetId(String streetId) {
		this.streetId = streetId;
	}

	@Column(name = "addr_detail")
	public String getAddrDetail() {
		return this.addrDetail;
	}

	public void setAddrDetail(String addrDetail) {
		this.addrDetail = addrDetail;
	}
	
	@Column(name = "hos_key")
	public String getHosKey() {
		return hosKey;
	}

	public void setHosKey(String hosKey) {
		this.hosKey = hosKey;
	}

}
